import { supabase } from './lib/supabase.js';
import { preparePhoto, objectUrl } from './lib/image.js';
import { buildRewritePrompt } from './lib/editorialStyle.js';
import { enablePush, notifyWorkflow } from './lib/push.js';

const state={user:null,profile:null,photos:[],installPrompt:null};
const statusLabels={draft:'Szkic',submitted:'Nowe',editing:'Do redakcji',awaiting_author:'Czeka na autora',changes_requested:'Poprawka autora',approved:'Zaakceptowane',published:'Opublikowane',rejected:'Wstrzymane'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>d?new Intl.DateTimeFormat('pl-PL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d)):'';

export async function startApp(root){
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;render(root)});
  const {data:{session}}=await supabase.auth.getSession(); state.user=session?.user||null;
  if(state.user) await loadProfile();
  supabase.auth.onAuthStateChange(async(_e,s)=>{state.user=s?.user||null;state.profile=null;if(state.user)await loadProfile();render(root)});
  render(root);
}
async function loadProfile(){const {data}=await supabase.from('profiles').select('*').eq('id',state.user.id).maybeSingle();state.profile=data||null}
function top(){return `<div class="topbar"><div class="brand"><img src="/icons/icon.svg" alt=""><span>MOW Fanpage</span></div><div class="nav">${state.installPrompt?'<button class="install" data-install>Zainstaluj</button>':''}${state.user?'<button data-home>Start</button><button data-new>Nowy materiał</button><button data-mine>Moje</button>':''}${state.profile?.role==='moderator'?'<button data-mod>Moderator</button>':''}${state.user?'<button data-logout>Wyloguj</button>':''}</div></div>`}
function bindGlobal(root){root.querySelector('[data-install]')?.addEventListener('click',async()=>{await state.installPrompt.prompt();state.installPrompt=null;render(root)});root.querySelector('[data-home]')?.addEventListener('click',()=>home(root));root.querySelector('[data-new]')?.addEventListener('click',()=>newSubmission(root));root.querySelector('[data-mine]')?.addEventListener('click',()=>mySubmissions(root));root.querySelector('[data-mod]')?.addEventListener('click',()=>moderator(root));root.querySelector('[data-logout]')?.addEventListener('click',()=>supabase.auth.signOut())}
function page(root,body){root.innerHTML=top()+`<main class="shell">${body}</main>`;bindGlobal(root)}
function render(root){if(!state.user)return login(root);if(!state.profile)return profileSetup(root);home(root)}

function login(root){page(root,`<section class="login card"><h1>MOW Fanpage</h1><p>Bezpieczne przekazywanie materiałów do publikacji.</p><form data-login><label>E-mail pracownika<input type="email" name="email" required autocomplete="email"></label><div class="actions"><button class="primary">Wyślij kod / link logowania</button></div><p class="hint">Logowanie jest jednorazowo potwierdzane przez Supabase Auth. Materiały i zdjęcia nie są wysyłane pocztą.</p><p class="status" data-status></p></form></section>`);root.querySelector('[data-login]').addEventListener('submit',async e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');const st=root.querySelector('[data-status]');st.textContent='Wysyłanie…';const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});st.textContent=error?error.message:'Sprawdź skrzynkę i dokończ logowanie.'})}
function profileSetup(root){page(root,`<section class="login card"><h1>Pierwsze uruchomienie</h1><form data-profile><label>Imię i nazwisko<input name="full_name" required maxlength="120"></label><label>Szkoła / internat / grupa<input name="unit" required maxlength="120"></label><div class="actions"><button class="primary">Zapisz profil</button></div><p class="status" data-status></p></form></section>`);root.querySelector('[data-profile]').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const {error}=await supabase.from('profiles').insert({id:state.user.id,full_name:fd.get('full_name'),unit:fd.get('unit'),role:'employee'});if(error)root.querySelector('[data-status]').textContent=error.message;else{await loadProfile();home(root)}})}
function home(root){page(root,`<section class="hero"><h1>Materiały do fanpage'a MOW</h1><p>Zdjęcia, opis, kontrola zgód, redakcja i akceptacja w jednym miejscu.</p></section><section class="card"><h2>${esc(state.profile.full_name)}</h2><p>${esc(state.profile.unit)}</p><div class="actions"><button class="primary" data-new2>+ Nowy materiał</button><button class="secondary" data-mine2>Moje materiały</button>${state.profile.role==='moderator'?'<button class="secondary" data-mod2>Panel moderatora</button>':''}<button class="secondary" data-push>Włącz powiadomienia</button></div><p class="status" data-status></p></section>`);root.querySelector('[data-new2]').onclick=()=>newSubmission(root);root.querySelector('[data-mine2]').onclick=()=>mySubmissions(root);root.querySelector('[data-mod2]')&&(root.querySelector('[data-mod2]').onclick=()=>moderator(root));root.querySelector('[data-push]').onclick=async()=>{const st=root.querySelector('[data-status]');try{const r=await enablePush(state.user.id);st.textContent=r.ok?'Powiadomienia włączone.':'Powiadomienia push nie są jeszcze skonfigurowane na tym wdrożeniu.';st.className='status '+(r.ok?'ok':'')}catch(e){st.textContent=e.message}}}

function newSubmission(root){state.photos=[];page(root,`<section class="hero"><h1>Nowy materiał</h1><p>Wypełnij, dodaj maksymalnie 15 zdjęć i wyślij moderatorowi.</p></section><form data-form>
<section class="card"><h2>1. Wydarzenie</h2><div class="grid"><label class="wide">Tytuł / temat<input name="title" required maxlength="180"></label><label>Data wydarzenia<input type="date" name="event_date" required></label><label>Miejsce<input name="location" required maxlength="160"></label><label class="wide">Tekst / opis<textarea name="body_original" rows="8" required maxlength="10000" placeholder="Wklej gotowy tekst albo opisz najważniejsze fakty."></textarea></label><label class="wide">Uwagi tylko dla moderatora<textarea name="editor_notes" rows="3" maxlength="3000"></textarea></label></div></section>
<section class="card"><h2>2. Zdjęcia</h2><p class="hint">Do 15 zdjęć. Kopia wysyłana do systemu zostanie przeskalowana i ponownie zapisana jako JPEG, co usuwa EXIF/GPS.</p><label class="drop">Wybierz zdjęcia z telefonu<input data-photos type="file" accept="image/*" multiple></label><div class="photos" data-photo-list></div><p class="status" data-photo-status></p></section>
<section class="card"><h2>3. Jak potraktować tekst?</h2><div class="radio-row"><label><input type="radio" name="editorial_mode" value="edit_approval" checked><span><b>Przeredaguj w stylu fanpage'a MOW i odeślij mi do akceptacji</b><br><span class="hint">Moderator przygotuje wersję końcową. Dostaniesz ją w aplikacji do zatwierdzenia.</span></span></label><label><input type="radio" name="editorial_mode" value="original"><span><b>Zachowaj mój tekst w oryginalnym brzmieniu</b><br><span class="hint">Moderator może wstrzymać element niedopuszczalny prawnie, ale nie zmienia stylu bez kontaktu z Tobą.</span></span></label></div></section>
<section class="card"><h2>4. Status wizerunku</h2><div class="radio-row"><label><input type="radio" name="consent_status" value="verified" required><span><b>Zgody / podstawy sprawdzone</b> — rozpoznawalne osoby mogą być opublikowane w planowanym zakresie.</span></label><label><input type="radio" name="consent_status" value="group_shots"><span><b>Tylko szerokie ujęcia</b> — osoby są elementem większej całości, nie głównym tematem.</span></label><label><input type="radio" name="consent_status" value="needs_review"><span><b>Proszę o weryfikację</b> — nie jestem pewien/-na co najmniej jednego zdjęcia.</span></label></div></section>
<section class="card checks"><h2>5. Potwierdzenia</h2>${checksHtml()}</section>
<div class="actions"><button class="primary" type="submit">Sprawdź i wyślij</button></div><p class="status" data-status></p></form>`);
const input=root.querySelector('[data-photos]');input.onchange=()=>selectPhotos(root,[...input.files]);root.querySelector('[data-form]').onsubmit=e=>submitMaterial(root,e)}
function checksHtml(){return [
 ['rights_confirmed','Jestem autorem przesłanych zdjęć i tekstu albo mam prawo przekazać je MOW do publikacji.'],
 ['consents_verified','Sprawdziłem/-am podstawę publikacji wizerunku osób rozpoznawalnych albo oznaczyłem/-am materiał jako wymagający weryfikacji.'],
 ['safe_content_confirmed','Materiał nie zawiera informacji o diagnozach, terapii, karach, postępowaniach, sytuacji rodzinnej ani innych danych wrażliwych.'],
 ['youth_objection_checked','Żadna osoba będąca głównym bohaterem zdjęcia nie zgłosiła mi sprzeciwu wobec publikacji.'],
 ['accuracy_confirmed','Potwierdzam prawdziwość i rzetelność przekazanych przeze mnie informacji.']
].map(([n,t])=>`<label><input type="checkbox" name="${n}" required><span>${t}</span></label>`).join('')}
async function selectPhotos(root,files){const st=root.querySelector('[data-photo-status]');if(files.length>15){st.textContent='Maksymalnie 15 zdjęć.';return}st.textContent='Przygotowywanie zdjęć…';state.photos=[];for(const f of files){try{const p=await preparePhoto(f);state.photos.push(p)}catch(e){st.textContent=e.message;return}}renderThumbs(root);st.textContent=`Gotowe: ${state.photos.length} / 15`;st.className='status ok'}
function renderThumbs(root){const box=root.querySelector('[data-photo-list]');box.innerHTML=state.photos.map((f,i)=>`<div class="thumb"><img src="${objectUrl(f)}" alt="Zdjęcie ${i+1}"><button type="button" data-rm="${i}">×</button></div>`).join('');box.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{state.photos.splice(+b.dataset.rm,1);renderThumbs(root)})}
async function submitMaterial(root,e){e.preventDefault();const st=root.querySelector('[data-status]');if(!state.photos.length){st.textContent='Dodaj co najmniej jedno zdjęcie.';return}const fd=new FormData(e.currentTarget);const payload={author_id:state.user.id,title:fd.get('title'),event_date:fd.get('event_date'),location:fd.get('location'),body_original:fd.get('body_original'),editor_notes:fd.get('editor_notes'),editorial_mode:fd.get('editorial_mode'),consent_status:fd.get('consent_status'),rights_confirmed:true,consents_verified:true,safe_content_confirmed:true,youth_objection_checked:true,accuracy_confirmed:true,status:'draft'};st.textContent='Zapisywanie…';const {data:sub,error}=await supabase.from('submissions').insert(payload).select().single();if(error){st.textContent=error.message;return}for(let i=0;i<state.photos.length;i++){const f=state.photos[i], path=`${state.user.id}/${sub.id}/${String(i+1).padStart(2,'0')}-${f.name}`;const up=await supabase.storage.from('mow-materials').upload(path,f,{contentType:'image/jpeg',upsert:false});if(up.error){st.textContent=`Błąd zdjęcia ${i+1}: ${up.error.message}`;return}const pr=await supabase.from('submission_photos').insert({submission_id:sub.id,storage_path:path,order_index:i,uploaded_by:state.user.id});if(pr.error){st.textContent=pr.error.message;return}}
const {error:rpc}=await supabase.rpc('submit_submission',{p_submission_id:sub.id});if(rpc){st.textContent=rpc.message;return}await notifyWorkflow('submitted',sub.id);state.photos=[];detail(root,sub.id)}

async function mySubmissions(root){page(root,`<section class="hero"><h1>Moje materiały</h1></section><section class="card"><div class="list" data-list>Ładowanie…</div></section>`);const {data,error}=await supabase.from('submissions').select('id,title,status,consent_status,created_at,event_date').eq('author_id',state.user.id).order('created_at',{ascending:false});const box=root.querySelector('[data-list]');if(error){box.textContent=error.message;return}box.innerHTML=data.length?data.map(itemHtml).join(''):'Brak materiałów.';box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>detail(root,b.dataset.open))}
function itemHtml(x){return `<div class="item"><div class="item-head"><b>${esc(x.title)}</b><span class="badge s-${esc(x.status)}">${statusLabels[x.status]||x.status}</span></div><span class="muted">${esc(x.event_date||'')} · ${fmt(x.created_at)}</span>${x.consent_status==='needs_review'?'<span class="badge s-needs_review">RODO — sprawdź</span>':''}<div><button class="secondary" data-open="${x.id}">Otwórz</button></div></div>`}
async function detail(root,id){const {data:s,error}=await supabase.from('submissions').select('*,profiles!submissions_author_id_fkey(full_name,unit),submission_photos(*)').eq('id',id).single();if(error){page(root,`<p>${esc(error.message)}</p>`);return}const {data:revs}=await supabase.from('revisions').select('*').eq('submission_id',id).order('version_no',{ascending:false});const latest=revs?.[0];const signed=[];for(const p of (s.submission_photos||[]).sort((a,b)=>a.order_index-b.order_index)){const {data}=await supabase.storage.from('mow-materials').createSignedUrl(p.storage_path,600);if(data?.signedUrl)signed.push(data.signedUrl)}page(root,`<section class="hero"><h1>${esc(s.title)}</h1><p><span class="badge s-${s.status}">${statusLabels[s.status]||s.status}</span></p></section><section class="card"><b>Autor:</b> ${esc(s.profiles?.full_name)} — ${esc(s.profiles?.unit)}<p>${esc(s.location)} · ${esc(s.event_date)}</p><h3>Tekst źródłowy</h3><p>${esc(s.body_original).replace(/\n/g,'<br>')}</p><div class="photos">${signed.map(u=>`<div class="thumb"><img src="${esc(u)}" alt=""></div>`).join('')}</div></section>${latest?`<section class="card"><h2>Wersja redakcyjna nr ${latest.version_no}</h2><p>${esc(latest.content).replace(/\n/g,'<br>')}</p>${s.author_id===state.user.id&&s.status==='awaiting_author'?`<label>Uwagi do poprawki<textarea data-comment rows="3"></textarea></label><div class="actions"><button class="primary" data-approve>Akceptuję wersję</button><button class="secondary" data-changes>Proszę o poprawkę</button></div>`:''}</section>`:''}${s.published_url?`<section class="card"><a class="primary" href="${esc(s.published_url)}" target="_blank" rel="noopener">Otwórz opublikowany post</a></section>`:''}`);if(root.querySelector('[data-approve]'))root.querySelector('[data-approve]').onclick=()=>respond(root,latest.id,true,'',id);if(root.querySelector('[data-changes]'))root.querySelector('[data-changes]').onclick=()=>respond(root,latest.id,false,root.querySelector('[data-comment]').value,id)}
async function respond(root,revisionId,approved,comment,subId){const {error}=await supabase.rpc('respond_to_revision',{p_revision_id:revisionId,p_approved:approved,p_comment:comment||null});if(error)return alert(error.message);await notifyWorkflow(approved?'approved':'changes_requested',subId);detail(root,subId)}

async function moderator(root){if(state.profile.role!=='moderator')return home(root);page(root,`<section class="hero"><h1>Panel moderatora</h1><p>Nowe → redakcja → akceptacja autora → publikacja.</p></section><section class="card"><div class="list" data-list>Ładowanie…</div></section>`);const {data,error}=await supabase.from('submissions').select('id,title,status,consent_status,created_at,event_date,profiles!submissions_author_id_fkey(full_name,unit)').order('created_at',{ascending:false});const box=root.querySelector('[data-list]');if(error){box.textContent=error.message;return}box.innerHTML=data.length?data.map(x=>`<div class="item"><div class="item-head"><b>${esc(x.title)}</b><span class="badge s-${x.status}">${statusLabels[x.status]||x.status}</span></div><span>${esc(x.profiles?.full_name)} — ${esc(x.profiles?.unit)}</span>${x.consent_status==='needs_review'?'<span class="badge s-needs_review">RODO — sprawdź</span>':''}<div><button class="secondary" data-edit="${x.id}">Otwórz / redaguj</button></div></div>`).join(''):'Brak zgłoszeń.';box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>moderateOne(root,b.dataset.edit))}
async function moderateOne(root,id){const {data:s,error}=await supabase.from('submissions').select('*,profiles!submissions_author_id_fkey(full_name,unit)').eq('id',id).single();if(error)return alert(error.message);const {data:revs}=await supabase.from('revisions').select('*').eq('submission_id',id).order('version_no',{ascending:false});const latest=revs?.[0];page(root,`<section class="hero"><h1>${esc(s.title)}</h1><p>${esc(s.profiles.full_name)} — <span class="badge s-${s.status}">${statusLabels[s.status]||s.status}</span></p></section>${s.consent_status==='needs_review'?'<div class="notice">⚠️ Autor oznaczył materiał jako wymagający weryfikacji zgód przed publikacją.</div>':''}<section class="card editor-columns"><div><h2>Tekst źródłowy</h2><textarea rows="18" readonly>${esc(s.body_original)}</textarea><button class="secondary" data-copy-prompt>Kopiuj prompt redakcyjny</button></div><div><h2>Wersja do publikacji</h2><textarea data-edit-text rows="18">${esc(latest?.content||s.body_original)}</textarea><div class="actions"><button class="primary" data-send-rev>Wyślij autorowi do akceptacji</button></div></div></section><section class="card"><h2>Publikacja</h2><label>Link do gotowego posta na Facebooku<input data-url type="url" placeholder="https://www.facebook.com/..."></label><div class="actions"><button class="primary" data-published>Oznacz jako opublikowane</button></div><p class="status" data-status></p></section>`);root.querySelector('[data-copy-prompt]').onclick=async()=>{await navigator.clipboard.writeText(buildRewritePrompt(s.body_original));root.querySelector('[data-copy-prompt]').textContent='Skopiowano'};root.querySelector('[data-send-rev]').onclick=async()=>{const content=root.querySelector('[data-edit-text]').value.trim();if(!content)return;const {error}=await supabase.rpc('create_revision_and_send',{p_submission_id:id,p_content:content});if(error)return alert(error.message);await notifyWorkflow('revision_ready',id);moderateOne(root,id)};root.querySelector('[data-published]').onclick=async()=>{const url=root.querySelector('[data-url]').value.trim();const st=root.querySelector('[data-status]');if(!url){st.textContent='Wklej link do posta.';return}const {error}=await supabase.rpc('mark_published',{p_submission_id:id,p_url:url});if(error){st.textContent=error.message;return}await notifyWorkflow('published',id);moderateOne(root,id)}}
