import { supabase } from './lib/supabase.js';
import { preparePhoto, objectUrl } from './lib/image.js';
import { notifyWorkflow } from './lib/push.js';

const state={user:null,profile:null,photos:[],installPrompt:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={draft:'Szkic',submitted:'Nowe',editing:'Do redakcji',awaiting_author:'Czeka na autora',changes_requested:'Do poprawki',approved:'Zaakceptowane',published:'Opublikowane',rejected:'Wstrzymane'};
const entry=()=>location.pathname.startsWith('/admin')?'admin':'employee';

export async function startApp(root){
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;render(root)});
 const {data:{session}}=await supabase.auth.getSession();state.user=session?.user||null;if(state.user)await loadProfile();
 supabase.auth.onAuthStateChange(async(_e,s)=>{state.user=s?.user||null;state.profile=null;if(state.user)await loadProfile();render(root)});
 render(root);
}
async function loadProfile(){const {data}=await supabase.from('mow_profiles').select('*').eq('id',state.user.id).maybeSingle();state.profile=data||null}
function shell(root,body){root.innerHTML=`<header class="topbar"><div class="brand"><img src="/icons/icon.svg" alt=""><span>MOW Fanpage</span></div><nav class="nav">${state.installPrompt?'<button data-install>Zainstaluj</button>':''}${state.user&&state.profile?'<button data-home>Start</button><button data-new>Nowy materiał</button><button data-mine>Moje</button>':''}${state.profile?.role==='moderator'?'<button data-admin>Administrator</button>':''}${state.user?'<button data-out>Wyloguj</button>':''}</nav></header><main class="shell">${body}</main>`;bind(root)}
function bind(root){root.querySelector('[data-install]')?.addEventListener('click',async()=>{await state.installPrompt.prompt();state.installPrompt=null});root.querySelector('[data-home]')?.addEventListener('click',()=>home(root));root.querySelector('[data-new]')?.addEventListener('click',()=>newMaterial(root));root.querySelector('[data-mine]')?.addEventListener('click',()=>mine(root));root.querySelector('[data-admin]')?.addEventListener('click',()=>admin(root));root.querySelector('[data-out]')?.addEventListener('click',()=>supabase.auth.signOut())}
function render(root){if(!state.user)return login(root);if(!state.profile)return setup(root);if(entry()==='admin'&&state.profile.role==='moderator')return admin(root);home(root)}
function login(root){shell(root,`<section class="card login"><h1>${entry()==='admin'?'Panel administratora':'Materiały do fanpage’a MOW'}</h1><p>Zaloguj się służbowym adresem e-mail. Każdy wychowawca widzi wyłącznie własne materiały.</p><form data-login><label>E-mail<input type="email" name="email" required autocomplete="email"></label><div class="actions"><button class="primary">Wyślij link logowania</button></div><p data-status class="status"></p></form></section>`);root.querySelector('[data-login]').onsubmit=async e=>{e.preventDefault();const st=root.querySelector('[data-status]');const email=new FormData(e.currentTarget).get('email');st.textContent='Wysyłanie…';const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.href.split('#')[0]}});st.textContent=error?error.message:'Link logowania został wysłany na podany adres.'}}
function setup(root){shell(root,`<section class="card login"><h1>Pierwsze uruchomienie</h1><form data-profile><label>Imię i nazwisko<input name="name" required maxlength="120"></label><label>Szkoła / internat / grupa<input name="unit" required maxlength="120"></label><div class="actions"><button class="primary">Utwórz profil</button></div><p data-status class="status"></p></form></section>`);root.querySelector('[data-profile]').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),st=root.querySelector('[data-status]');const {error}=await supabase.rpc('mow_create_profile',{p_full_name:fd.get('name'),p_unit:fd.get('unit')});if(error)return st.textContent=error.message;await loadProfile();render(root)}}
function home(root){shell(root,`<section class="hero"><h1>Materiały do fanpage’a MOW</h1><p>${esc(state.profile.full_name)} · ${esc(state.profile.unit)}</p></section><section class="card"><h2>Co chcesz zrobić?</h2><div class="actions"><button class="primary" data-n>+ Dodaj materiał</button><button class="secondary" data-m>Moje materiały</button>${state.profile.role==='moderator'?'<button class="secondary" data-a>Panel administratora</button>':''}</div><p class="hint">Zdjęcia są przechowywane w prywatnym magazynie. Inni wychowawcy nie mają do nich dostępu.</p></section>`);root.querySelector('[data-n]').onclick=()=>newMaterial(root);root.querySelector('[data-m]').onclick=()=>mine(root);root.querySelector('[data-a]')&&(root.querySelector('[data-a]').onclick=()=>admin(root))}
function checks(){return [['rights_confirmed','Mam prawo przekazać ten tekst i zdjęcia do publikacji przez MOW.'],['consents_verified','Sprawdziłem/-am podstawę publikacji wizerunku albo oznaczyłem/-am materiał jako wymagający weryfikacji.'],['safe_content_confirmed','Materiał nie zawiera danych wrażliwych ani informacji o terapii, karach, postępowaniach lub sytuacji rodzinnej.'],['youth_objection_checked','Żadna osoba będąca głównym bohaterem zdjęcia nie zgłosiła mi sprzeciwu wobec publikacji.'],['accuracy_confirmed','Potwierdzam prawdziwość przekazanych informacji.']].map(([n,t])=>`<label><input type="checkbox" name="${n}" required> <span>${t}</span></label>`).join('')}
function newMaterial(root){state.photos=[];shell(root,`<section class="hero"><h1>Nowy materiał</h1><p>Opis wydarzenia i maksymalnie piętnaście zdjęć.</p></section><form data-form><section class="card"><h2>Wydarzenie</h2><div class="grid"><label class="wide">Tytuł<input name="title" required maxlength="180"></label><label>Data<input type="date" name="date" required></label><label>Miejsce<input name="location" required maxlength="160"></label><label class="wide">Tekst / opis<textarea name="body" rows="8" required maxlength="10000"></textarea></label><label class="wide">Uwagi dla administratora<textarea name="notes" rows="3" maxlength="3000"></textarea></label></div></section><section class="card"><h2>Zdjęcia</h2><p class="hint">Do piętnastu zdjęć. Kopie są skalowane i ponownie zapisywane jako JPEG, co usuwa EXIF/GPS.</p><label class="drop">Wybierz zdjęcia<input data-files type="file" accept="image/*" multiple></label><div class="photos" data-photos></div><p data-photo-status class="status"></p></section><section class="card"><h2>Redakcja tekstu</h2><div class="radio-row"><label><input type="radio" name="mode" value="original" checked> Zachowaj mój tekst; administrator może go skrócić/redakcyjnie poprawić.</label><label><input type="radio" name="mode" value="edit_approval"> Odeślij mi wersję redakcyjną do akceptacji.</label></div></section><section class="card"><h2>Status wizerunku</h2><div class="radio-row"><label><input type="radio" name="consent" value="verified" required> Zgody / podstawy sprawdzone</label><label><input type="radio" name="consent" value="group_shots"> Tylko szerokie ujęcia wydarzenia</label><label><input type="radio" name="consent" value="needs_review"> Proszę administratora o weryfikację</label></div></section><section class="card checks"><h2>Potwierdzenia</h2>${checks()}</section><div class="actions"><button class="primary">Wyślij administratorowi</button></div><p data-status class="status"></p></form>`);const f=root.querySelector('[data-files]');f.onchange=()=>photos(root,[...f.files]);root.querySelector('[data-form]').onsubmit=e=>send(root,e)}
async function photos(root,files){const st=root.querySelector('[data-photo-status]');if(files.length>15)return st.textContent='Maksymalnie piętnaście zdjęć.';state.photos=[];st.textContent='Przygotowywanie…';for(const f of files){try{state.photos.push(await preparePhoto(f))}catch(e){return st.textContent=e.message}}thumbs(root);st.textContent=`Gotowe: ${state.photos.length} / 15`}
function thumbs(root){const b=root.querySelector('[data-photos]');b.innerHTML=state.photos.map((f,i)=>`<div class="thumb"><img src="${objectUrl(f)}"><button type="button" data-rm="${i}">×</button></div>`).join('');b.querySelectorAll('[data-rm]').forEach(x=>x.onclick=()=>{state.photos.splice(+x.dataset.rm,1);thumbs(root)})}
async function send(root,e){e.preventDefault();const st=root.querySelector('[data-status]');if(!state.photos.length)return st.textContent='Dodaj co najmniej jedno zdjęcie.';const fd=new FormData(e.currentTarget),payload={author_id:state.user.id,title:fd.get('title'),event_date:fd.get('date'),location:fd.get('location'),body_original:fd.get('body'),editor_notes:fd.get('notes'),editorial_mode:fd.get('mode'),consent_status:fd.get('consent'),rights_confirmed:true,consents_verified:true,safe_content_confirmed:true,youth_objection_checked:true,accuracy_confirmed:true,status:'draft'};st.textContent='Zapisywanie…';const {data:s,error}=await supabase.from('mow_submissions').insert(payload).select().single();if(error)return st.textContent=error.message;for(let i=0;i<state.photos.length;i++){const f=state.photos[i],path=`${state.user.id}/${s.id}/${String(i+1).padStart(2,'0')}-${f.name}`;const up=await supabase.storage.from('mow-materials').upload(path,f,{contentType:'image/jpeg'});if(up.error)return st.textContent=up.error.message;const db=await supabase.from('mow_submission_photos').insert({submission_id:s.id,storage_path:path,order_index:i,uploaded_by:state.user.id});if(db.error)return st.textContent=db.error.message}const {error:rpc}=await supabase.rpc('mow_submit_submission',{p_submission_id:s.id});if(rpc)return st.textContent=rpc.message;await notifyWorkflow('submitted',s.id);state.photos=[];detail(root,s.id)}
async function mine(root){shell(root,`<section class="hero"><h1>Moje materiały</h1></section><section class="card"><div data-list>Ładowanie…</div></section>`);const {data,error}=await supabase.from('mow_submissions').select('id,title,status,event_date,consent_status').order('created_at',{ascending:false});const b=root.querySelector('[data-list]');if(error)return b.textContent=error.message;b.innerHTML=data?.length?data.map(item).join(''):'Nie masz jeszcze materiałów.';b.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>detail(root,x.dataset.open))}
function item(x){return `<div class="item"><div class="item-head"><b>${esc(x.title)}</b><span class="badge">${labels[x.status]||esc(x.status)}</span></div><span class="muted">${esc(x.event_date)}</span>${x.consent_status==='needs_review'?'<span class="badge">Wymaga weryfikacji</span>':''}<div><button class="secondary" data-open="${x.id}">Otwórz</button></div></div>`}
async function detail(root,id){const {data:s,error}=await supabase.from('mow_submissions').select('*,mow_profiles!mow_submissions_author_id_fkey(full_name,unit),mow_submission_photos(*)').eq('id',id).single();if(error)return shell(root,`<section class="card">${esc(error.message)}</section>`);const urls=[];for(const p of (s.mow_submission_photos||[]).sort((a,b)=>a.order_index-b.order_index)){const {data}=await supabase.storage.from('mow-materials').createSignedUrl(p.storage_path,600);if(data?.signedUrl)urls.push(data.signedUrl)}shell(root,`<section class="hero"><h1>${esc(s.title)}</h1><p>${labels[s.status]||esc(s.status)}</p></section><section class="card"><p><b>Autor:</b> ${esc(s.mow_profiles?.full_name||state.profile.full_name)} · ${esc(s.mow_profiles?.unit||state.profile.unit)}</p><p>${esc(s.event_date)} · ${esc(s.location)}</p><h3>Tekst</h3><p>${esc(s.body_original).replace(/\n/g,'<br>')}</p><div class="photos">${urls.map(u=>`<div class="thumb"><img src="${esc(u)}"></div>`).join('')}</div>${s.published_url?`<p><a href="${esc(s.published_url)}" target="_blank" rel="noopener">Zobacz publikację</a></p>`:''}</section>`)}
async function admin(root){if(state.profile?.role!=='moderator')return home(root);shell(root,`<section class="hero"><h1>Panel administratora</h1><p>Wszystkie materiały przekazane do moderacji.</p></section><section class="card"><div data-list>Ładowanie…</div></section>`);const {data,error}=await supabase.from('mow_submissions').select('id,title,status,event_date,consent_status,author_id,mow_profiles!mow_submissions_author_id_fkey(full_name,unit)').order('created_at',{ascending:false});const b=root.querySelector('[data-list]');if(error)return b.textContent=error.message;b.innerHTML=data?.length?data.map(x=>`<div class="item"><div class="item-head"><b>${esc(x.title)}</b><span class="badge">${labels[x.status]||x.status}</span></div><span>${esc(x.mow_profiles?.full_name)} · ${esc(x.mow_profiles?.unit)}</span>${x.consent_status==='needs_review'?'<span class="badge">WIZERUNEK — sprawdź</span>':''}<div><button class="secondary" data-open="${x.id}">Otwórz</button></div></div>`).join(''):'Brak materiałów.';b.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>detail(root,x.dataset.open))}
